name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Thank you for your contribution to the Automation repository. Your pull request has been received and will be reviewed shortly. Please ensure it follows the project's guidelines as outlined in the CONTRIBUTING.md file."
